# Generated by Django 3.0.6 on 2020-05-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Golfers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('team', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
