# Generated by Django 3.0.6 on 2020-05-27 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Golfers',
            new_name='Golfer',
        ),
    ]
