# Generated by Django 3.0.6 on 2020-06-01 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_handicap_hole_schedule_score_subrecord_tiebreaker'),
    ]

    operations = [
        migrations.RenameModel('Handicap', 'HandicapSet')
    ]
