# Generated by Django 3.0.6 on 2020-06-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200601_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handicap',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('golfer', models.IntegerField()),
                ('handicap', models.IntegerField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
