# Generated by Django 3.0.6 on 2020-06-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_handicap'),
    ]

    operations = [
        migrations.RenameModel('Schedule', 'ScheduleSet')
    ]
