# Generated by Django 3.0.6 on 2020-06-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200601_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('team1', models.IntegerField()),
                ('team2', models.IntegerField()),
                ('week', models.IntegerField()),
                ('front', models.BooleanField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
