# Generated by Django 3.0.6 on 2020-06-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_matchup'),
    ]

    operations = [
        migrations.AddField(
            model_name='hole',
            name='year',
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
    ]
