# Generated by Django 3.0.6 on 2020-06-01 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_hole_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hole',
            new_name='HoleOld',
        ),
    ]
