# Generated by Django 3.0.6 on 2020-06-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200601_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hole', models.IntegerField()),
                ('par', models.IntegerField()),
                ('handicap', models.IntegerField()),
                ('handicap9', models.IntegerField()),
                ('yards', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
