# Generated by Django 3.0.6 on 2020-07-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_hole'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandicapReal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('golfer', models.IntegerField()),
                ('handicap', models.FloatField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
