# Generated by Django 3.0.6 on 2020-09-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_handicapreal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Handicap',
        ),
        migrations.DeleteModel(
            name='HandicapSet',
        ),
        migrations.DeleteModel(
            name='HoleOld',
        ),
        migrations.DeleteModel(
            name='ScheduleSet',
        ),
        migrations.AlterField(
            model_name='golfer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='handicapreal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hole',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subrecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
