# Generated by Django 3.0.6 on 2020-08-10 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_handicapreal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Handicap',
        ),
        migrations.DeleteModel(
            name='HandicapSet',
        ),
        migrations.DeleteModel(
            name='HoleOld',
        ),
        migrations.DeleteModel(
            name='ScheduleSet',
        ),
        migrations.RenameField(
            model_name='golfer',
            old_name='team',
            new_name='team_id',
        ),
        migrations.AddField(
            model_name='handicapreal',
            name='golfer_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Golfer'),
        ),
        migrations.AddField(
            model_name='score',
            name='golfer_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Golfer'),
        ),
        migrations.AddField(
            model_name='score',
            name='hole_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Hole'),
        ),
        migrations.AlterField(
            model_name='golfer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='handicapreal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hole',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subrecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='team',
            name='golfers',
            field=models.ManyToManyField(to='main.Golfer'),
        ),
        migrations.AddField(
            model_name='golfer',
            name='team_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Team'),
        ),
    ]
