# Generated by Django 3.0.6 on 2020-08-15 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200810_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='golfer',
            old_name='team_id',
            new_name='team',
        ),
        migrations.RemoveField(
            model_name='golfer',
            name='team_fk',
        ),
        migrations.RemoveField(
            model_name='handicapreal',
            name='golfer_fk',
        ),
        migrations.RemoveField(
            model_name='score',
            name='golfer_fk',
        ),
        migrations.RemoveField(
            model_name='score',
            name='hole_fk',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
