# Generated by Django 3.0.6 on 2020-09-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200906_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('golfer', models.IntegerField()),
                ('opp', models.IntegerField()),
                ('front', models.BooleanField()),
                ('opp_net', models.IntegerField()),
                ('opp_gross', models.IntegerField()),
                ('opp_points', models.IntegerField()),
                ('opp_hcp', models.FloatField()),
                ('hcp', models.FloatField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
                ('points', models.FloatField()),
                ('gross', models.IntegerField()),
                ('pars', models.IntegerField()),
                ('birdies', models.IntegerField()),
                ('bogies', models.IntegerField()),
                ('doubles', models.IntegerField()),
                ('triples', models.IntegerField()),
                ('worse', models.IntegerField()),
                ('net', models.IntegerField()),
                ('std_dev', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
