# Generated by Django 3.0.6 on 2020-09-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='fours',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
