# Generated by Django 3.0.6 on 2020-09-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_round_fours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='bogies',
            new_name='bogeys',
        ),
        migrations.AlterField(
            model_name='round',
            name='opp_points',
            field=models.FloatField(),
        ),
    ]
