# Generated by Django 3.1.7 on 2021-05-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_golfer_established'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('golfer', models.IntegerField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
                ('won', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkinEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('golfer', models.IntegerField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
                ('won', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
