# Generated by Django 3.1.7 on 2021-05-16 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_gameentry_skin_skinentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameentry',
            name='year',
        ),
        migrations.RemoveField(
            model_name='skinentry',
            name='year',
        ),
    ]
