# Generated by Django 3.1.7 on 2021-05-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210516_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameentry',
            name='year',
            field=models.IntegerField(default=2021),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skinentry',
            name='year',
            field=models.IntegerField(default=2021),
            preserve_default=False,
        ),
    ]
