# Generated by Django 3.2.3 on 2021-06-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210516_1826'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='golfer',
            index=models.Index(fields=['year', 'id'], name='main_golfer_year_8dc7e3_idx'),
        ),
        migrations.AddIndex(
            model_name='handicapreal',
            index=models.Index(fields=['year', 'week', 'golfer'], name='main_handic_year_72319b_idx'),
        ),
        migrations.AddIndex(
            model_name='hole',
            index=models.Index(fields=['year', 'hole'], name='main_hole_year_25c53c_idx'),
        ),
        migrations.AddIndex(
            model_name='matchup',
            index=models.Index(fields=['year', 'week'], name='main_matchu_year_7c7929_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['golfer', 'week', 'year'], name='main_score_golfer_259fc2_idx'),
        ),
    ]
