# Generated by Django 3.2.3 on 2021-06-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210625_2254'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='golfer',
            index=models.Index(fields=['team', 'year'], name='main_golfer_team_3db713_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['golfer', 'week'], name='main_score_golfer_08cd61_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['week', 'year'], name='main_score_week_49f3f7_idx'),
        ),
    ]
